branch-defaults:
  master:
    environment: sippa-no-api
global:
  application_name: sippa-no-api
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2016.03 v2.1.6 running Docker 1.11.2
  default_region: us-east-1
  profile: sippa
  sc: git
